"""add fil model

Revision ID: a5624ce5cecb
Revises: 10b465640dde
Create Date: 2021-06-30 21:40:18.086028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5624ce5cecb'
down_revision = '10b465640dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('length', sa.Float(), nullable=True))
    op.drop_column('films', 'lenght')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('lenght', sa.FLOAT(), nullable=True))
    op.drop_column('films', 'length')
    # ### end Alembic commands ###
